services:
  app:
    image: repo.strolch.li/docker/pillow-desk:latest
    container_name: pillow-desk
    hostname: app
    ports:
      - 127.0.0.1:8085:8080
    environment:
      - TZ=Europe/Zurich
      - STROLCH_ENV=test
      - STROLCH_PATH=/strolch
    volumes:
      - ./strolch:/strolch
      - ./logs:/usr/local/tomcat/logs
    restart: unless-stopped
