package ch.eitchnet.pillowdesk.rest;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import li.strolch.model.Order;
import li.strolch.model.ParameterBag;
import li.strolch.model.StrolchModelConstants;
import li.strolch.model.json.StrolchRootElementToJsonVisitor;
import li.strolch.model.parameter.DateParameter;
import li.strolch.model.parameter.IntegerParameter;
import li.strolch.model.parameter.StringParameter;
import org.junit.jupiter.api.Test;

import java.util.Date;

import static ch.eitchnet.pillowdesk.core.model.ModelConstants.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class StayResourceTest extends AbstractPillowDeskRestfulTest {

	@Test
	void shouldManageStays() {
		String authToken = authenticate();

		// 1. Add
		Order stay = new Order("stay1", "Stay 1", TYPE_STAY);
		ParameterBag bag = new ParameterBag(BAG_PARAMETERS, "Parameters", "Parameters");
		bag.addParameter(new StringParameter(PARAM_GUEST_NAME, "Guest Name", "John Doe"));
		bag.addParameter(new StringParameter(PARAM_BOOKING_ID, "Booking ID", "B123"));
		bag.addParameter(new DateParameter(PARAM_CHECK_IN, "Check-In", new Date()));
		bag.addParameter(
				new DateParameter(PARAM_CHECK_OUT, "Check-Out", new Date(System.currentTimeMillis() + 86400000)));
		bag.addParameter(new IntegerParameter(PARAM_ADULTS, "Adults", 2));
		bag.addParameter(new IntegerParameter(PARAM_CHILDREN, "Children", 0));
		stay.addParameterBag(bag);

		ParameterBag relationsBag = new ParameterBag(BAG_RELATIONS, "Relations", "Relations");
		StringParameter roomParam = new StringParameter(PARAM_ROOM, "Room", "room_1");
		roomParam.setInterpretation(StrolchModelConstants.INTERPRETATION_RESOURCE_REF);
		roomParam.setUom(TYPE_ROOM);
		relationsBag.addParameter(roomParam);
		StringParameter rateParam = new StringParameter(PARAM_RATE, "Rate", "rate_standard");
		rateParam.setInterpretation(StrolchModelConstants.INTERPRETATION_RESOURCE_REF);
		rateParam.setUom(TYPE_RATE);
		relationsBag.addParameter(rateParam);
		stay.addParameterBag(relationsBag);

		JsonObject stayJson = stay.accept(new StrolchRootElementToJsonVisitor());

		try (Response response = target()
				.path("pillowdesk/stays")
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.post(Entity.json(stayJson.toString()))) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
		}

		// Get the actual ID (as it is generated by the server)
		String actualId;
		try (Response response = target()
				.path("pillowdesk/stays")
				.queryParam("name", "John Doe")
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.get()) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
			JsonObject result = JsonParser.parseString(response.readEntity(String.class)).getAsJsonObject();
			JsonArray data = result.get("data").getAsJsonArray();
			assertEquals(1, data.size());
			actualId = data.get(0).getAsJsonObject().get("id").getAsString();
		}

		// 2. Get
		try (Response response = target()
				.path("pillowdesk/stays/" + actualId)
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.get()) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
			JsonObject result = JsonParser.parseString(response.readEntity(String.class)).getAsJsonObject();
			JsonObject data = result.get("data").getAsJsonObject();
			assertEquals("Stay 1", data.get("name").getAsString());

			// Verify totalRevenue is present
			JsonObject params = data
					.get("parameterBags")
					.getAsJsonObject()
					.get(BAG_PARAMETERS)
					.getAsJsonObject()
					.get("parameters")
					.getAsJsonObject();
			assertNotNull(params.get(PARAM_TOTAL_REVENUE), "totalRevenue should be present");
		}

		// 3. Search
		try (Response response = target()
				.path("pillowdesk/stays")
				.queryParam("name", "John")
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.get()) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
			JsonObject result = JsonParser.parseString(response.readEntity(String.class)).getAsJsonObject();
			JsonArray data = result.get("data").getAsJsonArray();
			assertEquals(1, data.size());
		}

		// 4. Update
		stay.setId(actualId);
		stay.setName("Updated Stay 1");
		stayJson = stay.accept(new StrolchRootElementToJsonVisitor());
		try (Response response = target()
				.path("pillowdesk/stays/" + actualId)
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.put(Entity.json(stayJson.toString()))) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
		}

		// 5. Delete
		try (Response response = target()
				.path("pillowdesk/stays/" + actualId)
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.delete()) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
		}

		// 6. Get again (should be 404)
		try (Response response = target()
				.path("pillowdesk/stays/" + actualId)
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.get()) {
			assertEquals(Response.Status.NOT_FOUND.getStatusCode(), response.getStatus());
		}
	}

	@Test
	void shouldCalculateStayCosts() {
		String authToken = authenticate();

		Order stay = new Order("stay_calc", "Stay Calc", TYPE_STAY);
		ParameterBag bag = new ParameterBag(BAG_PARAMETERS, "Parameters", "Parameters");
		bag.addParameter(new DateParameter(PARAM_CHECK_IN, "Check-In", new Date()));
		bag.addParameter(
				new DateParameter(PARAM_CHECK_OUT, "Check-Out", new Date(System.currentTimeMillis() + 2 * 86400000))); // 2 nights
		bag.addParameter(new IntegerParameter(PARAM_ADULTS, "Adults", 2));
		bag.addParameter(new IntegerParameter(PARAM_CHILDREN, "Children", 0));
		stay.addParameterBag(bag);

		ParameterBag relationsBag = new ParameterBag(BAG_RELATIONS, "Relations", "Relations");
		StringParameter rateParam = new StringParameter(PARAM_RATE, "Rate", "rate_standard");
		rateParam.setInterpretation(li.strolch.model.StrolchModelConstants.INTERPRETATION_RESOURCE_REF);
		rateParam.setUom(TYPE_RATE);
		relationsBag.addParameter(rateParam);
		stay.addParameterBag(relationsBag);

		JsonObject stayJson = stay.accept(new li.strolch.model.json.StrolchRootElementToJsonVisitor());

		try (Response response = target()
				.path("pillowdesk/stays/calculate")
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.post(Entity.json(stayJson.toString()))) {
			assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
			JsonObject result = JsonParser.parseString(response.readEntity(String.class)).getAsJsonObject();
			JsonObject data = result.get("data").getAsJsonObject();

			assertEquals(2, data.get("nights").getAsLong());
			assertEquals(8.0, data.get("touristTax").getAsDouble());
			assertEquals(108.0, data.get("totalRevenue").getAsDouble());
		}
	}

	@Test
	void shouldFailToCalculateStayCostsMissingRate() {
		String authToken = authenticate();

		Order stay = new Order("stay_calc_fail", "Stay Calc Fail", TYPE_STAY);
		ParameterBag bag = new ParameterBag(BAG_PARAMETERS, "Parameters", "Parameters");
		bag.addParameter(new DateParameter(PARAM_CHECK_IN, "Check-In", new Date()));
		bag.addParameter(
				new DateParameter(PARAM_CHECK_OUT, "Check-Out", new Date(System.currentTimeMillis() + 86400000)));
		stay.addParameterBag(bag);

		// No relations bag
		JsonObject stayJson = stay.accept(new li.strolch.model.json.StrolchRootElementToJsonVisitor());

		try (Response response = target()
				.path("pillowdesk/stays/calculate")
				.request(MediaType.APPLICATION_JSON)
				.header("Authorization", authToken)
				.post(Entity.json(stayJson.toString()))) {
			assertEquals(Response.Status.BAD_REQUEST.getStatusCode(), response.getStatus());
		}
	}
}
