<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ch.atexxi.pillowdesk</groupId>
        <artifactId>PillowDesk</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>pillow-desk-core</artifactId>
    <name>PillowDesk Core</name>

    <dependencies>
        <dependency>
            <groupId>li.strolch</groupId>
            <artifactId>strolch-model</artifactId>
        </dependency>
        <dependency>
            <groupId>li.strolch</groupId>
            <artifactId>strolch-service</artifactId>
        </dependency>
        <dependency>
            <groupId>li.strolch</groupId>
            <artifactId>strolch-persistence-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>li.strolch</groupId>
            <artifactId>strolch-test-base</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>li.strolch</groupId>-->
<!--            <artifactId>strolch-web-rest</artifactId>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->
    </dependencies>
</project>
